BookingTicketTrain/Models/Schedule.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookingTicketTrain.Models
{
    public class Schedule
    {
        [Key]
        public int ScheduleId { get; set; }
        public string CountryFrom { get; set; }
        public string CountryTo { get; set; }
        public string StationName { get; set; }
        public DateTime CreatedAt { get; set; }
        [StringLength(4)]
        public string Seat { get; set; }
    }
}

BookingTicketTrain/Controllers/ScheduleController.cs
using BookingTicketTrain.Models;
using BookingTicketTrain.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookingTicketTrain.Controllers
{
    public class ScheduleController : Controller
    {
        private readonly IScheduleServices scheduleServices;
        private readonly AppDbContext dbContext;

        public ScheduleController(IScheduleServices scheduleServices, AppDbContext dbContext)
        {
            this.scheduleServices = scheduleServices;
            this.dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult CreateSchedule()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateSchedule(Schedule model)
        {
            ViewBag.Result = false;
            if(ModelState.IsValid)
            {
                if(model.CountryFrom.Equals(model.CountryTo))
                {
                    ModelState.AddModelError("", "Destination country must be different from Starting country!");
                    ViewBag.Result = false;
                    return View(model);
                }
                var result = await scheduleServices.CreateSchedule(model);
                if(result)
                {
                    ViewBag.Result = true;
                    return View(model);
                }
                ModelState.AddModelError("", "This seat Already created!");
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> GetListSchedule(string desCountryName)
        {
            ViewBag.countryto = desCountryName;
            var schedules = dbContext.schedules.Where(x => x.CountryTo.Equals(desCountryName)).Select(x =>x);
            return View(schedules.ToList());
        }

        [HttpGet]
        public IActionResult GetListSchedule2()
        {
            return View();
        }

    }
}

BookingTicketTrain/Controllers/TicketController.cs
using BookingTicketTrain.Models;
using BookingTicketTrain.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace BookingTicketTrain.Controllers
{
    public class TicketController : Controller
    {
        private readonly AppDbContext dbContext;
        private readonly ITicketServices ticketServices;

        public TicketController(AppDbContext dbContext, ITicketServices ticketServices)
        {
            this.dbContext = dbContext;
            this.ticketServices = ticketServices;
        }

        [HttpPost]
        public async Task<IActionResult> BookingTicket(int scheId,string userId)
        {
            var id = userId;
            var result = await ticketServices.BookTicketAsync(scheId, id);
            if (result)
            {
                ViewBag.Message = "Success";
                return View("Response");
            }
            ViewBag.Message = "Failed";
            return View("Response");
        }
    }
}

BookingTicketTrain/Views/Schedule/CreateSchedule.cshtml
@{
    ViewData["Title"] = "Create Schedule";
    Layout = "_MyLayout";
}
@section Styles
{
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
    <style>

    </style>
}

@{ 
    var stationList = StationStore.AllStations;
    var seatList = SeatStore.AllSeats;
    var countryList = CountryStore.ListCountry;
}
@model BookingTicketTrain.Models.Schedule;

<div class="container"style="margin-top:120px;margin-bottom:120px;">
    <form asp-controller="Schedule" asp-action="CreateSchedule" method="post">
        <h2>Create new schedule</h2>
        <div class="row" style="margin-top:40px;">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="from">Country From</label>
                    <select id="from" class="form-control" asp-for="@Model.CountryFrom">
                        @foreach (var item in countryList)
                        {
                            <option value="@item">@item</option>
                        }
                    </select>                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label for="to">Country To</label>
                    <select id="to" class="form-control" asp-for="@Model.CountryTo">
                        @foreach (var item in countryList)
                        {
                            <option value="@item">@item</option>
                        }
                    </select>                </div>
            </div>
            <!--  col-md-6   -->
        </div>


        <div class="form-group">
            <label for="stationName">Station Name</label>
            <select id="stationName" class="form-control" asp-for="@Model.StationName">
                @foreach (var item in stationList)
                {
                    <option value="@item">@item</option>
                }
            </select>
        </div>

        <div class="form-group">
            <label for="seatName">Seat</label>
            <select id="seatName" class="form-control" asp-for="@Model.Seat">
                @foreach (var item in seatList)
                {
                    <option value="@item">@item</option>
                }
            </select>
        </div>

        <button type="submit" class="btn btn-primary" style="margin-top: 20px;">Create</button>
        <button type="reset" class="btn btn-light" style="margin-top: 20px;">Cancel</button><br /><br />
        @if (ViewBag.Result == true)
        {
            <span class="text-success">Create Successfully!</span>
        }
        else if(ViewBag.Result == false)
        {
            <span class="text-danger">Create Unsuccessfully!</span>
        }
        else
        {

        }
    </form>
    <div asp-validation-summary="All" class="text-danger"></div>
</div>

BookingTicketTrain/Views/Schedule/GetListSchedule.cshtml
@{
    ViewData["Title"] = "List Ticket";
    Layout = "_MyLayout";
}
@section Styles
{
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
    <style>
        body, h1, h2, h3, h4, h5, h6 {
            font-family: "Karma", sans-serif
        }

        .w3-bar-block .w3-bar-item {
            padding: 20px
        }
    </style>
}

@model List<Schedule>;

<!-- !PAGE CONTENT! -->
<div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:100px">
    <div class="w3-row-padding w3-padding-16 w3-center" id="food">
        <h3>Desnation: @ViewBag.countryto</h3>
    </div>
    <!-- First Photo Grid-->
    @foreach (var item in Model)
    {
        <form asp-controller="Ticket" asp-action="BookingTicket" method="post" style="display:inline-block;width:30%">
            <input type="hidden" value="@item.ScheduleId" name="scheId" />
            <input type="hidden" value="@GlobalVariables.UserId" name="userId"  />

            <div class="w3-row-padding w3-padding-16 w3-center" id="food">
                <div class="w3-quarter" style="width:100%">
                    <img src="https://booknookuk.com/wp-content/uploads/2019/10/ticket.jpg" alt="Sandwich" style="width:100%">
                    <h4><b>Country From:</b> @item.CountryFrom</h4>
                    <h4><b>Country To:</b> @item.CountryTo</h4>
                    <h4><b>Station:</b> @item.StationName</h4>
                    <h4><b>Seat</b>: @item.Seat</h4>
                    <button class="btn btn-primary">Book</button>
                </div>
            </div>
        </form>
    }


        @*Pagination
            <div class="w3-center w3-padding-32">
                <div class="w3-bar">
                    <a href="#" class="w3-bar-item w3-button w3-hover-black">«</a>
                    <a href="#" class="w3-bar-item w3-black w3-button">1</a>
                    <a href="#" class="w3-bar-item w3-button w3-hover-black">2</a>
                    <a href="#" class="w3-bar-item w3-button w3-hover-black">3</a>
                    <a href="#" class="w3-bar-item w3-button w3-hover-black">4</a>
                    <a href="#" class="w3-bar-item w3-button w3-hover-black">»</a>
                </div>
            </div>*@
        <!-- End page content -->
    </div>

<script>
    // Script to open and close sidebar
    function w3_open() {
        document.getElementById("mySidebar").style.display = "block";
    }

    function w3_close() {
        document.getElementById("mySidebar").style.display = "none";
    }
</script>